datanalyse/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from datanalyse import views as views1
from django.contrib.auth import views as views2
from datanalyse.forms import LoginForm
from django.contrib.auth.decorators import login_required
from datanalyse.forms import RegistrationForm



app_name="datanalyse"
urlpatterns = [

    #url(r'^$',  views.homeview, name='home'),
    #url(r'^(?P<username>[\w.@+-]+)/$',  views.UserPortsListView.as_view(), name='index'),
    url(r'^home/$',  login_required(views1.UserPortsListView.as_view()), name='index'),
    url(r'^$', views2.login, {'template_name': 'datanalyse/landingnew.html', 'authentication_form': LoginForm,},name='loggingin'),
    url(r'^logout/$', views2.logout, {'next_page': '/'},name='logout'),
    url(r'^register/$', views1.RegisterUser.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views1.DetailView.as_view()), name='detail'),
    url(r'^sell/(?P<pk>\d+)$', login_required(views1.SellStock.as_view()), name='sell-detail'),
    url(r'^ss/(?P<pk>\d+)$',  login_required(views1.Sell.as_view()), name='ss'),
    url(r'^howto/$',  login_required(views1.howtoview.as_view()), name='howto'),
    url(r'^buy/$',  login_required(views1.buyview.as_view()), name='buystock'),
    # url(r'^autocomplete/$',views1.AutoCompleteView.as_view(), name='autocomplete'),
    url(r'^news/$',  login_required(views1.newsView.as_view()), name='news'),
    url(r'^buys/$', login_required(views1.buy_category), name='buy_category'),
    url(r'^finalbuy/$', login_required(views1.FinalBuy.as_view()), name='finalbuy'),
    url(r'^learn/$',  login_required(views1.learnview.as_view()), name='learn'),
]

datanalyse/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models

# Create your models here.

class UserPorts(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    companies = models.CharField(max_length=15)
    quantity = models.IntegerField()
    boughtat = models.FloatField()

    def __str__(self):
        return (self.user).username

    def get_absolute_url(self):
        return reverse('datanalyse:detail',kwargs={'pk':self.pk})

class UserMoney(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    money=models.FloatField(default=2000000)

    def __str__(self):
        return (self.user).username

class TickerComp(models.Model):
    ticker = models.CharField(max_length=2000)
    name = models.CharField(max_length=2000)

    def __str__(self):
        return self.ticker

class BuyStockTable(models.Model):
    ticker = models.CharField(max_length=2000)
    name = models.CharField(max_length=2000)

    def __str__(self):
        return self.ticker

datanalyse/templates/datanalyse/buy.html
<!DOCTYPE html>
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<parent
        xmlns:svg="http://www.w3.org/2000/svg">
<html lang="en">
<head>


<title>Nvstrr</title>
    <meta charset="utf-8">

    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cormorant+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <style>

    #footer {
        clear: both;
        position: relative;
        z-index: 10;
        height: 3em;
        margin-top: -3em;
    }

  .page-current {
    border: 3px solid #444444;
    margin-left: 2px;
    margin-right: 2px;
    padding-left: 2px;
    }

    .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}



.dropdown:hover .dropdown-content {
    display: block;
}

#logout{
font-family:"Goudy Old Style", Garamond, Big Caslon, Times New Roman, serif !important;
font-size: 0.85em;
}




  </style>
</head>

<body>
<div class="se-pre-con" id="loader"></div>

<div class="navbar navbar-default navbar-fixed-top" style="font-family: 'Cormorant SC', serif; font-size:1.2em;">
      <div class="container-fluid ">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand animated slideInLeft" style="font-family: 'Junction-regular'; font-size:1.1em;"><b>nvstrr</b></a>

        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li ><a href="{% url 'datanalyse:index' %} ">Dashboard</a></li>
            <li><a href="{% url 'datanalyse:news' %}" >News</a></li>
            <li><a href="{% url 'datanalyse:howto' %}" >HowTo</a></li>
            <li><a href="{% url 'datanalyse:learn' %}" >Learn</a></li>
          </ul>


        <ul class="navbar-right nav navbar-nav">
          <li><a href="{% url 'datanalyse:buystock' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Buy Stocks
          </a></li>
           <li style="padding-right: 10px; line-height:50px;font-family: 'Goudy Old Style' ;"> Rs. {{money}} </li>
           <li style="margin-top:-5px; line-height:30px; margin-bottom: -50px; " class="dropdown"> <a href="#" class="dropbtn" ><i class="fa fa-user-circle-o" style="font-size:24px;line-height:25px;"> </i>   {{usern}} </a>

                <div class="dropdown-content">
                  <a href="{% url 'datanalyse:logout' %}" id="logout" >Logout</a>

                </div>

                </li>



        </ul>



        </div>
      </div>
    </div>

<br><br><br>
<div class="container-fluid">



    <div class="row" ><br>

      <div class="col-md-6 bgrey"  style=" padding-left:20px;padding-left:20px; border-right: 1px solid #ccc;">
        <h3 class="text-muted" align="left">Latest Information</h3><hr>
        <div class="row">

          <div class="col-md-12" ><center>
              <h4><div id="name" ></div></h4></center>
          </div>


            </div>
            <br>
            <div class="row">
              <div class="col-md-6 text-muted" style="padding-left:50px;">
                    <p align="left">Last<br>Change<br>% Change<br>Volume<br>Day's High<br>Day's Low</p>


              </div>
              <div class="col-md-6" style="padding-right:50px;" >
                  <p align="right"><span id="latest"></span><br>
                    <span id="c"></span><br>
                    <span id="cp"></span><br>
                    <span id="vo"></span><br>
                    <span id="hi"></span><br>
                    <span id="lo"></span>

                  </p>
              </div>

                </div>
      </div>

        <div class="col-md-6 bgrey">
          <h3 class="text-muted" align="left">Buy Stocks</h3>
        <hr>
          <div class="row">
            <div class="col-md-3">

              <div>  Company Ticker:
              </div>
              <br>
              <br>
                <div> Number of stocks:
                </div>
            </div>
            <div class="col-md-9">
          <div class="form-group">
            <form method="post" action="{% url 'datanalyse:finalbuy' %}">
                {% csrf_token %}

            <div class="col-md-4">

              <input list="tickers" id="ticks" class="form-control" name="ticks" required>
              <datalist id="tickers">
                {% for tick in tickers %}
                <option value="{{tick.ticker}}">
                  {% endfor %}
              </datalist>
            <br>

             <input type="number" min="0" class="form-control" name="stocks" required>
             <br>
             <input type="submit" onclick="return confirm('Are you sure?')" class="btn btn-success" value="Confirm Trade"/>
              </form>
            </div>
          </div>
        </div>

      </div>
          <!--<form>
           <input list="tickers" id="ticks" >
           <datalist id="tickers" >
             {% for tick in tickers %}
             <option value="{{tick.ticker}}">
               {% endfor %}
           </datalist>
          <input type="number" min="0">
        </form>-->
        </div>
    </div>
  </div>
  <div id="footer">
  <div class="container-fluid">
  <div class="row" style="margin-top:10px;margin-bottom:10px;">

    <div><center><p> Nvstrr &copy; 2016</p></center></div>

  </div>

  </div>
  </div>


<script>
/*$(document).ready(function(){
    $("#ticks").blur(function(){
        var element = $("#ticks").val();
        alert(element);
        var req = new XMLHttpRequest();
        req.open('GET', 'http://www.google.com/finance/info?infotype=infoquoteall&q=BOM:ONGC', false);
        req.responseType = 'text';
        //alert('1');
        req.onload = function () {
        if (req.readyState === req.DONE) {
        //  alert('2');
        if (req.status === 200) {
            console.log(req.response);
            console.log(req.responseText);
        //    alert('3');
        //    alert(req.response);
        //    alert(req.responseText);

        }
        //if(req.status == 200)
        //var jsob = JSON.parse(req.responseText);
        //alert(jsob);
        //req.send(null);

    });
});*//*
function getbuy()
{
  var element =document.getElementById("ticks").value;
    alert(element);
    var req = new XMLHttpRequest();
    req.open('GET', 'http://www.google.com/finance/info?infotype=infoquoteall&q=BOM:ONGC', false);
    req.responseType = 'text';
    req.onload = function () {
    if (req.readyState === req.DONE) {
    //  alert('2');
    if (req.status === 200) {
        console.log(req.response);
        console.log(req.responseText);
    }
  }
};
}*/

/*var xhr = new XMLHttpRequest();
xhr.onreadystatechange = function() {
    if (xhr.readyState == XMLHttpRequest.DONE) {
        alert(xhr.responseText);
    }
}
xhr.open('GET', 'http://www.google.com/finance/info?infotype=infoquoteall&q=BOM:ONGC', true);
xhr.send(null);*/
/*$.ajax({
    url: "http://www.google.com/finance/info?infotype=infoquoteall&q=BOM:ONGC",

    dataType: "jsonp",
    success: function( response ) {
        console.log( response );
        alert(response.c); // server response
    }

});*/
$('#ticks').blur(function(){
var tick;
tick = $("#ticks").val();
 $.get('/buys/', {comp : tick, thing:'last'}, function(data){
           $('#latest').html(data);
       });
$.get('/buys/', {comp : tick, thing:'name'}, function(data){
                 $('#name').html(data);
             });
             $.get('/buys/', {comp : tick, thing:'c'}, function(data){
                              $('#c').html(data);
                          });$.get('/buys/', {comp : tick, thing:'cp'}, function(data){
                                           $('#cp').html(data);
                                       });
                                       $.get('/buys/', {comp : tick, thing:'vo'}, function(data){
                                                        $('#vo').html(data);
                                                    });
                                                    $.get('/buys/', {comp : tick, thing:'lo'}, function(data){
                                                                     $('#lo').html(data);
                                                                 });
                                                                 $.get('/buys/', {comp : tick, thing:'hi'}, function(data){
                                                                                  $('#hi').html(data);
                                                                              });

});
</script>

</body>
</html>

datanalyse/templates/datanalyse/letsee.html
<!DOCTYPE html>
<html lang="en">
<head>

<title>Nvstrr</title>
    <meta charset="utf-8">

    {% load staticfiles %}
    {% load current_val %}


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cormorant+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <style>
  #inctab {
    counter-reset: serial-number;  /* Set the serial number counter to 0 */
  }

  #inctab td:first-child:before {
    counter-increment: serial-number;  /* Increment the serial number counter */
    content: counter(serial-number);  /* Display the counter */
  }

    #footer {
        clear: both;
        position: relative;
        z-index: 10;
        height: 3em;
        margin-top: -3em;
    }


  .searchbox{
      position:relative;
      min-width:23px;
      width:0%;
      height:23px;
      float:right;
      overflow:hidden;

      -webkit-transition: width 0.3s;
      -moz-transition: width 0.3s;
      -ms-transition: width 0.3s;
      -o-transition: width 0.3s;
      transition: width 0.3s;
  }

  .searchbox-input{
      top:0;
      right:0;
      border:0;
      outline:0;
      background:#b2ceea;/*#557391;/*#dcddd8;*/
      width:100%;
      height:23px;
      margin:0;
      padding:0px 55px 0px 20px;
      font-size:20px;
      color:##12181e;
  }
  .searchbox-input::-webkit-input-placeholder {
      color: #1c2630;/*#d74b4b;*/
  }
  .searchbox-input:-moz-placeholder {
      color: #1c2630;/*#d74b4b;*/
  }
  .searchbox-input::-moz-placeholder {
      color: #1c2630;/*#d74b4b;*/
  }
  .searchbox-input:-ms-input-placeholder {
      color: #1c2630;/*#d74b4b;*/
  }

  .searchbox-icon,
  .searchbox-submit{
      width:23px;
      height:23px;
      display:block;
      position:absolute;
      top:0;
      font-family:verdana;
      font-size:15px;
      right:0;
      padding:0;
      margin:0;
      border:0;
      outline:0;
      line-height:23px;
      text-align:center;
      cursor:pointer;
      color:#dcddd8;
      background:#172b3c;
  }



  .searchbox-open{
      width:100%;
  }


  /*.page-current {
    border: 3px solid #444444;
    margin-left: 2px;
    margin-right: 2px;
    padding-left: 2px;
    }*/

    .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
    text-align: left;
}



.dropdown:hover .dropdown-content {
    display: block;
}

#logout{
font-family:"Goudy Old Style", Garamond, Big Caslon, Times New Roman, serif !important;
font-size: 0.85em;
}
/*.row.vdivide {
background: #e0e0e0;
  width: 1px;
  content: "";
  position: relative;

}*/
  </style>
</head>

<body>
<div class="navbar navbar-default navbar-fixed-top" style="font-family: 'Cormorant SC', serif; font-size:1.2em;">
      <div class="container-fluid ">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand animated slideInLeft" style="font-family: 'Junction-regular'; font-size:1.1em;"><b>nvstrr</b></a>

        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li ><a href="{% url 'datanalyse:index' %} ">Dashboard</a></li>
            <li><a href="{% url 'datanalyse:news' %}" >News</a></li>
            <li><a href="{% url 'datanalyse:howto' %}" >HowTo</a></li>
            <li><a href="{% url 'datanalyse:learn' %}" >Learn</a></li>
          </ul>


        <ul class="navbar-right nav navbar-nav">
          <li><a href="{% url 'datanalyse:buystock' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Buy Stocks
          </a></li>
           <li style="padding-right: 10px; line-height:50px;font-family: 'Goudy Old Style' ;"> Rs. {{money}} </li>
           <li style="margin-top:-5px; line-height:30px; margin-bottom: -50px; " class="dropdown"> <a href="#" class="dropbtn" ><i class="fa fa-user-circle-o" style="font-size:24px;line-height:25px;"> </i>   {{usern}} </a>

                <div class="dropdown-content">
                  <a href="{% url 'datanalyse:logout' %}" id="logout" >Logout</a>

                </div>

                </li>



        </ul>



        </div>
      </div>
    </div>

<br><br><br>


<div class="container-fluid " >
  <div class="row" >
    <div class="col-md-3"  style=" padding-left:20px;padding-left:20px;">
      <!--Sidebar content-->
      <h4 class="text-muted" align="left">Leaderboard</h4><hr>
      <table class="table table-striped" id ="inctab">

      <thead class="thead-default">
      <tr class="text-muted">
        <b>
        <th>Rank</th>
        <th>Username</th>
        <th>Current Money</th>
      </b>
      </tr>
      </thead>
      {% for l in leaderboard %}
      <tr>
        <td></td>
        <td>{{l}}</td>
        <td>{{l.money}}</td>
      </tr>
      {% endfor %}
    </table>
    </div>
    <div class="col-md-9 section"  style="padding-left:20px; border-left: 1px solid #ccc;height: 100%;min-height:100%;">
      <!--Body content-->
      <div class="container" style="width:300px;margin:20px auto;" id="searchform" action="{% url 'datanalyse:index' %}" method="get" accept-charset="utf-8">
      <form class="searchbox">
          <input type="search"  name="q" placeholder="Search Tickers" name="search" class="searchbox-input" onkeyup="buttonUp();">
          <input type="submit" class="searchbox-submit" value="GO">
          <span class="searchbox-icon"><i class="fa fa-search" aria-hidden="true"></i>
    </span>
      </form>
    </div>
      <hr>
      <h4 class="text-muted" align="left">My Portfolio</h4>
<hr>
    <table class="table table-condensed">

    <thead class="thead-default">
    <tr class="text-muted">
      <b>
      <th></th>
      <th>Company name</th>
      <th>Qty</th>
      <th>Purchase Price</th>
      <th>Current Price</th>
      <th>Total Value</th>
      <th>Total Gain/Loss</th>
      <th>More Information</th>
    </b>
    </tr>
    </thead>
    {% if userports_list %}
    {% for userp in userports_list %}
      <tr>
        <td><a href="{% url 'datanalyse:sell-detail' userp.id %}">Sell</a></td>
        <td>{{ userp.companies}}</td>
        <td>{{ userp.quantity }}</td>
        <td>Rs. {{ userp.boughtat }}</td>
        <td>Rs. {% cur_val  userp.companies %}</td>
        <td>Rs. {% tot_val  userp.companies userp.quantity %}</td>
        {% tot_gl  userp.companies userp.quantity userp.boughtat as gainloss %}
        {% if gainloss < 0 %}
                <td style="color:red;">Rs. {{gainloss}}</td>
        {% else %}
              <td style="color:green;">Rs. {{gainloss}}</td>
          {% endif %}
        <td><a href="{% url 'datanalyse:detail' userp.id %}"><i class="fa fa-info-circle" style="font-size:20px;font-color:#b2ceea;"></i></a></td>
      </tr>
         {% endfor %}

       </table>

    </div>
  </div>
</div>


{% if is_paginated %}
<center>
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-left" style="font-size:20px;font-color:#1c2630;" aria-hidden="true"></i>&nbsp;</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">&nbsp;<i class="fa fa-arrow-right" style="font-size:20px;font-color:#1c2630;" aria-hidden="true"></i></a>
            {% endif %}
        </span>
    </div>
  </center>
  <hr>
{% endif %}
{% else %}
<h3>My Stocks</h3>
<p>No stocks found!!! :(</p>
{% endif %}


<div id="footer">
<div class="container-fluid">
<div class="row" style="margin-top:10px;margin-bottom:10px;">

  <div><center><p> Nvstrr &copy; 2016</p></center></div>

</div>

</div>
</div>

<script>
$(document).ready(function(){
        var submitIcon = $('.searchbox-icon');
        var inputBox = $('.searchbox-input');
        var searchBox = $('.searchbox');
        var isOpen = false;
        submitIcon.click(function(){
            if(isOpen == false){
                searchBox.addClass('searchbox-open');
                inputBox.focus();
                isOpen = true;
            } else {
                searchBox.removeClass('searchbox-open');
                inputBox.focusout();
                isOpen = false;
            }
        });
         submitIcon.mouseup(function(){
                return false;
            });
        searchBox.mouseup(function(){
                return false;
            });
        $(document).mouseup(function(){
                if(isOpen == true){
                    $('.searchbox-icon').css('display','block');
                    submitIcon.click();
                }
            });
    });
        function buttonUp(){
            var inputVal = $('.searchbox-input').val();
            inputVal = $.trim(inputVal).length;
            if( inputVal !== 0){
                $('.searchbox-icon').css('display','none');
            } else {
                $('.searchbox-input').val('');
                $('.searchbox-icon').css('display','block');
            }
        }
</script>
</body>
</html>

datanalyse/templates/datanalyse/letsee1.html
<!DOCTYPE html>
<html lang="en">
<head>

<title>Nvstrr</title>
    <meta charset="utf-8">

    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cormorant+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <style>

  .page-current {
    border: 3px solid #444444;
    margin-left: 2px;
    margin-right: 2px;
    padding-left: 2px;
    }
  </style>
</head>

<body>
<div class="navbar navbar-default navbar-fixed-top" style="font-family: 'Cormorant SC', serif; font-size:1.2em;">
      <div class="container-fluid ">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand animated slideInLeft" style="font-family: 'Junction-regular'; font-size:1.1em;"><b>nvstrr</b></a>

        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#topr">&nbsp;Dashboard</a></li>
            <li><a href="#mid " >&nbsp;News</a></li>
            <li><a href="#team" >&nbsp;My Profile</a></li>
          </ul>

            <form class="navbar-form navbar-right">
                <button type="submit" formmethod="get" formaction="{% url 'datanalyse:logout' %}">LOGOUT</button>
            </form>


        </div>
      </div>
    </div>

<br><br><br>

<form id="searchform" action="{% url 'datanalyse:index' %}" method="get" accept-charset="utf-8">
  {% csrf_token %}
  <button class="searchbutton" type="submit">
    GO<!--<i class="fa fa-search"></i>-->
  </button>
  <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
</form>

<h1>Hi
{{usern}}
{{money}}
</h1>
{% if userports_list %}
    <table id="userports">
        {% for userp in userports_list %}
            <tr>
                <td>{{ userp.companies}}</td>
                <td>{{ userp.quantity }}</td>
                <td>{{ userp.boughtat }}</td>
                <td><a href="{% url 'datanalyse:detail' userp.id %}">info</a></td>
            </tr>
        {% endfor %}
    </table>
    {# .... **Now the pagination section** .... #}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% else %}
    <h3>My Stocks</h3>
    <p>No stocks found!!! :(</p>
{% endif %}
</body>
</html>